use soroban_sdk::{Address,Env,String};use crate::types::*;use common::pause;
const BK:soroban_sdk::Symbol=soroban_sdk::symbol_short!("bal");const AK:soroban_sdk::Symbol=soroban_sdk::symbol_short!("allow");const DK:soroban_sdk::Symbol=soroban_sdk::symbol_short!("del");
pub fn init(env:&Env,admin:&Address,name:String,symbol:String,decimals:u32){admin.require_auth();env.storage().instance().set(&DataKey::Admin,admin);env.storage().instance().set(&DataKey::Metadata,&TokenMetadata{name,symbol,decimals});env.storage().instance().set(&DataKey::TotalSupply,&0i128);}
pub fn mint(env:&Env,admin:&Address,to:&Address,amount:i128)->Result<(),TokenError>{pause::when_not_paused(env).map_err(|_|TokenError::ContractPaused)?;admin.require_auth();let s:Address=env.storage().instance().get(&DataKey::Admin).ok_or(TokenError::NotInitialized)?;if admin!=&s{return Err(TokenError::Unauthorized);}if amount<=0{return Err(TokenError::InvalidAmount);}let supply:i128=env.storage().instance().get(&DataKey::TotalSupply).unwrap_or(0);env.storage().instance().set(&DataKey::TotalSupply,&supply.checked_add(amount).ok_or(TokenError::InvalidAmount)?);let b:i128=env.storage().persistent().get(&(to,BK)).unwrap_or(0);env.storage().persistent().set(&(to,BK),&b.checked_add(amount).ok_or(TokenError::InvalidAmount)?);TokensMinted{to:to.clone(),amount}.publish(env);Ok(())}
pub fn transfer(env:&Env,from:&Address,to:&Address,amount:i128)->Result<(),TokenError>{pause::when_not_paused(env).map_err(|_|TokenError::ContractPaused)?;from.require_auth();if from==to{return Err(TokenError::SelfTransfer);}if amount<=0{return Err(TokenError::InvalidAmount);}let fb:i128=env.storage().persistent().get(&(from,BK)).unwrap_or(0);if fb<amount{return Err(TokenError::InsufficientBalance);}env.storage().persistent().set(&(from,BK),&fb.checked_sub(amount).ok_or(TokenError::InsufficientBalance)?);let tb:i128=env.storage().persistent().get(&(to,BK)).unwrap_or(0);env.storage().persistent().set(&(to,BK),&tb.checked_add(amount).ok_or(TokenError::InvalidAmount)?);TokensTransferred{from:from.clone(),to:to.clone(),amount}.publish(env);Ok(())}
pub fn burn(env:&Env,holder:&Address,amount:i128)->Result<(),TokenError>{pause::when_not_paused(env).map_err(|_|TokenError::ContractPaused)?;holder.require_auth();if amount<=0{return Err(TokenError::InvalidAmount);}let b:i128=env.storage().persistent().get(&(holder,BK)).unwrap_or(0);if b<amount{return Err(TokenError::InsufficientBalance);}env.storage().persistent().set(&(holder,BK),&b.checked_sub(amount).ok_or(TokenError::InsufficientBalance)?);let supply:i128=env.storage().instance().get(&DataKey::TotalSupply).unwrap_or(0);env.storage().instance().set(&DataKey::TotalSupply,&supply.checked_sub(amount).ok_or(TokenError::InvalidAmount)?);TokensBurned{holder:holder.clone(),amount}.publish(env);Ok(())}
pub fn delegate(env:&Env,from:&Address,to:&Address)->Result<(),TokenError>{pause::when_not_paused(env).map_err(|_|TokenError::ContractPaused)?;from.require_auth();if from==to{return Err(TokenError::SameDelegate);}env.storage().persistent().set(&(from,DK),to);VotesDelegated{delegator:from.clone(),delegate_to:to.clone()}.publish(env);Ok(())}
pub fn approve(env:&Env,owner:&Address,spender:&Address,amount:i128,lul:u32)->Result<(),TokenError>{pause::when_not_paused(env).map_err(|_|TokenError::ContractPaused)?;owner.require_auth();if amount<0{return Err(TokenError::InvalidAmount);}env.storage().persistent().set(&(owner,spender,AK),&AllowanceEntry{owner:owner.clone(),spender:spender.clone(),amount,live_until_ledger:lul});Ok(())}
pub fn transfer_from(env:&Env,spender:&Address,from:&Address,to:&Address,amount:i128)->Result<(),TokenError>{pause::when_not_paused(env).map_err(|_|TokenError::ContractPaused)?;spender.require_auth();if amount<=0{return Err(TokenError::InvalidAmount);}let al:AllowanceEntry=env.storage().persistent().get(&(from,spender,AK)).ok_or(TokenError::InsufficientAllowance)?;if env.ledger().sequence()>al.live_until_ledger{return Err(TokenError::AllowanceExpired);}if al.amount<amount{return Err(TokenError::InsufficientAllowance);}let fb:i128=env.storage().persistent().get(&(from,BK)).unwrap_or(0);if fb<amount{return Err(TokenError::InsufficientBalance);}env.storage().persistent().set(&(from,BK),&fb.checked_sub(amount).ok_or(TokenError::InsufficientBalance)?);let tb:i128=env.storage().persistent().get(&(to,BK)).unwrap_or(0);env.storage().persistent().set(&(to,BK),&tb.checked_add(amount).ok_or(TokenError::InvalidAmount)?);env.storage().persistent().set(&(from,spender,AK),&AllowanceEntry{amount:al.amount-amount,..al});TokensTransferred{from:from.clone(),to:to.clone(),amount}.publish(env);Ok(())}
pub fn balance(env:&Env,addr:&Address)->i128{env.storage().persistent().get(&(addr,BK)).unwrap_or(0)}
pub fn allowance(env:&Env,owner:&Address,spender:&Address)->i128{let al:Option<AllowanceEntry>=env.storage().persistent().get(&(owner,spender,AK));match al{Some(e)=>if env.ledger().sequence()<=e.live_until_ledger{e.amount}else{0},None=>0}}
pub fn get_votes(env:&Env,addr:&Address)->i128{let mut d=addr.clone();for _ in 0..5{let dk=d.clone();let del:Option<Address>=env.storage().persistent().get(&(dk,DK));match del{Some(x)if x==d=>break,Some(x)=>d=x,None=>break}}env.storage().persistent().get(&(d,BK)).unwrap_or(0)}
pub fn decimals(env:&Env)->u32{let m:Option<TokenMetadata>=env.storage().instance().get(&DataKey::Metadata);m.map(|m|m.decimals).unwrap_or(7)}
pub fn name(env:&Env)->String{let m:Option<TokenMetadata>=env.storage().instance().get(&DataKey::Metadata);m.map(|m|m.name).unwrap_or_else(||String::from_str(env,"?"))}
pub fn symbol(env:&Env)->String{let m:Option<TokenMetadata>=env.storage().instance().get(&DataKey::Metadata);m.map(|m|m.symbol).unwrap_or_else(||String::from_str(env,"?"))}
pub fn pause(env:&Env,a:&Address)->Result<(),TokenError>{let s:Address=env.storage().instance().get(&DataKey::Admin).ok_or(TokenError::NotInitialized)?;if a!=&s{return Err(TokenError::Unauthorized);}pause::pause(env,a).map_err(|_|TokenError::ContractPaused)}
pub fn unpause(env:&Env,a:&Address)->Result<(),TokenError>{let s:Address=env.storage().instance().get(&DataKey::Admin).ok_or(TokenError::NotInitialized)?;if a!=&s{return Err(TokenError::Unauthorized);}pause::unpause(env,a).map_err(|_|TokenError::ContractPaused)}
